# Site settings
title: Fablab For Kids
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  un posto dove raccogliere progetti maker / educativi legati al mondo dei pi√π piccoli 
baseurl: /folioTest # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown
highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  schede:
    output: true
    permalink: /schede/:path/
#  poetry:
#   output: true
#   permalink: /poetry/:path/


